import logging


PERCEPTION_FREQUENCY = 20

APOLLO_VEHICLE_LENGTH = 4.70
APOLLO_VEHICLE_WIDTH = 2.06
APOLLO_VEHICLE_HEIGHT = 2.05

APOLLO_ROOT = '/home/yuqi/ResearchWorkspace/apollo'

STREAM_LOGGING_LEVEL = logging.DEBUG
