# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/v2x/proto/v2x_obu_traffic_light.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from modules.common.proto import header_pb2 as modules_dot_common_dot_proto_dot_header__pb2
from modules.v2x.proto import v2x_traffic_light_pb2 as modules_dot_v2x_dot_proto_dot_v2x__traffic__light__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/v2x/proto/v2x_obu_traffic_light.proto',
  package='apollo.v2x.obu',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n-modules/v2x/proto/v2x_obu_traffic_light.proto\x12\x0e\x61pollo.v2x.obu\x1a!modules/common/proto/header.proto\x1a)modules/v2x/proto/v2x_traffic_light.proto\"\x98\x03\n\x12SingleTrafficLight\x12\x33\n\x05\x63olor\x18\x01 \x01(\x0e\x32$.apollo.v2x.SingleTrafficLight.Color\x12\x1a\n\x12traffic_light_type\x18\x02 \x01(\x05\x12\n\n\x02id\x18\x03 \x01(\t\x12\x1e\n\x16\x63olor_remaining_time_s\x18\x04 \x01(\x05\x12\x18\n\x10right_turn_light\x18\x05 \x01(\x08\x12\x38\n\nnext_color\x18\x06 \x01(\x0e\x32$.apollo.v2x.SingleTrafficLight.Color\x12\x1b\n\x13next_remaining_time\x18\x07 \x01(\x01\x12<\n\x0enext_2nd_color\x18\x08 \x01(\x0e\x32$.apollo.v2x.SingleTrafficLight.Color\x12\x1f\n\x17next_2nd_remaining_time\x18\t \x01(\x01\"5\n\x04Type\x12\x0c\n\x08STRAIGHT\x10\x01\x12\x08\n\x04LEFT\x10\x02\x12\t\n\x05RIGHT\x10\x03\x12\n\n\x06U_TURN\x10\x04\"v\n\x10LaneTrafficLight\x12\x0f\n\x07gps_x_m\x18\x01 \x01(\x01\x12\x0f\n\x07gps_y_m\x18\x02 \x01(\x01\x12@\n\x14single_traffic_light\x18\x03 \x03(\x0b\x32\".apollo.v2x.obu.SingleTrafficLight\"h\n\x10RoadTrafficLight\x12<\n\x12lane_traffic_light\x18\x01 \x03(\x0b\x32 .apollo.v2x.obu.LaneTrafficLight\x12\x16\n\x0eroad_direction\x18\x02 \x01(\x05\"\xaa\x01\n\x0fObuTrafficLight\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.apollo.common.Header\x12<\n\x12road_traffic_light\x18\x02 \x03(\x0b\x32 .apollo.v2x.obu.RoadTrafficLight\x12\x17\n\x0fintersection_id\x18\x03 \x01(\x05\x12\x19\n\x11hdmap_junction_id\x18\x04 \x01(\x0c')
  ,
  dependencies=[modules_dot_common_dot_proto_dot_header__pb2.DESCRIPTOR,modules_dot_v2x_dot_proto_dot_v2x__traffic__light__pb2.DESCRIPTOR,])



_SINGLETRAFFICLIGHT_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='apollo.v2x.obu.SingleTrafficLight.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STRAIGHT', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LEFT', index=1, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RIGHT', index=2, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='U_TURN', index=3, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=499,
  serialized_end=552,
)
_sym_db.RegisterEnumDescriptor(_SINGLETRAFFICLIGHT_TYPE)


_SINGLETRAFFICLIGHT = _descriptor.Descriptor(
  name='SingleTrafficLight',
  full_name='apollo.v2x.obu.SingleTrafficLight',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='color', full_name='apollo.v2x.obu.SingleTrafficLight.color', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='traffic_light_type', full_name='apollo.v2x.obu.SingleTrafficLight.traffic_light_type', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='apollo.v2x.obu.SingleTrafficLight.id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='color_remaining_time_s', full_name='apollo.v2x.obu.SingleTrafficLight.color_remaining_time_s', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='right_turn_light', full_name='apollo.v2x.obu.SingleTrafficLight.right_turn_light', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='next_color', full_name='apollo.v2x.obu.SingleTrafficLight.next_color', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='next_remaining_time', full_name='apollo.v2x.obu.SingleTrafficLight.next_remaining_time', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='next_2nd_color', full_name='apollo.v2x.obu.SingleTrafficLight.next_2nd_color', index=7,
      number=8, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='next_2nd_remaining_time', full_name='apollo.v2x.obu.SingleTrafficLight.next_2nd_remaining_time', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SINGLETRAFFICLIGHT_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=552,
)


_LANETRAFFICLIGHT = _descriptor.Descriptor(
  name='LaneTrafficLight',
  full_name='apollo.v2x.obu.LaneTrafficLight',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gps_x_m', full_name='apollo.v2x.obu.LaneTrafficLight.gps_x_m', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gps_y_m', full_name='apollo.v2x.obu.LaneTrafficLight.gps_y_m', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='single_traffic_light', full_name='apollo.v2x.obu.LaneTrafficLight.single_traffic_light', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=554,
  serialized_end=672,
)


_ROADTRAFFICLIGHT = _descriptor.Descriptor(
  name='RoadTrafficLight',
  full_name='apollo.v2x.obu.RoadTrafficLight',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lane_traffic_light', full_name='apollo.v2x.obu.RoadTrafficLight.lane_traffic_light', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='road_direction', full_name='apollo.v2x.obu.RoadTrafficLight.road_direction', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=674,
  serialized_end=778,
)


_OBUTRAFFICLIGHT = _descriptor.Descriptor(
  name='ObuTrafficLight',
  full_name='apollo.v2x.obu.ObuTrafficLight',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='apollo.v2x.obu.ObuTrafficLight.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='road_traffic_light', full_name='apollo.v2x.obu.ObuTrafficLight.road_traffic_light', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='intersection_id', full_name='apollo.v2x.obu.ObuTrafficLight.intersection_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hdmap_junction_id', full_name='apollo.v2x.obu.ObuTrafficLight.hdmap_junction_id', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=781,
  serialized_end=951,
)

_SINGLETRAFFICLIGHT.fields_by_name['color'].enum_type = modules_dot_v2x_dot_proto_dot_v2x__traffic__light__pb2._SINGLETRAFFICLIGHT_COLOR
_SINGLETRAFFICLIGHT.fields_by_name['next_color'].enum_type = modules_dot_v2x_dot_proto_dot_v2x__traffic__light__pb2._SINGLETRAFFICLIGHT_COLOR
_SINGLETRAFFICLIGHT.fields_by_name['next_2nd_color'].enum_type = modules_dot_v2x_dot_proto_dot_v2x__traffic__light__pb2._SINGLETRAFFICLIGHT_COLOR
_SINGLETRAFFICLIGHT_TYPE.containing_type = _SINGLETRAFFICLIGHT
_LANETRAFFICLIGHT.fields_by_name['single_traffic_light'].message_type = _SINGLETRAFFICLIGHT
_ROADTRAFFICLIGHT.fields_by_name['lane_traffic_light'].message_type = _LANETRAFFICLIGHT
_OBUTRAFFICLIGHT.fields_by_name['header'].message_type = modules_dot_common_dot_proto_dot_header__pb2._HEADER
_OBUTRAFFICLIGHT.fields_by_name['road_traffic_light'].message_type = _ROADTRAFFICLIGHT
DESCRIPTOR.message_types_by_name['SingleTrafficLight'] = _SINGLETRAFFICLIGHT
DESCRIPTOR.message_types_by_name['LaneTrafficLight'] = _LANETRAFFICLIGHT
DESCRIPTOR.message_types_by_name['RoadTrafficLight'] = _ROADTRAFFICLIGHT
DESCRIPTOR.message_types_by_name['ObuTrafficLight'] = _OBUTRAFFICLIGHT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SingleTrafficLight = _reflection.GeneratedProtocolMessageType('SingleTrafficLight', (_message.Message,), dict(
  DESCRIPTOR = _SINGLETRAFFICLIGHT,
  __module__ = 'modules.v2x.proto.v2x_obu_traffic_light_pb2'
  # @@protoc_insertion_point(class_scope:apollo.v2x.obu.SingleTrafficLight)
  ))
_sym_db.RegisterMessage(SingleTrafficLight)

LaneTrafficLight = _reflection.GeneratedProtocolMessageType('LaneTrafficLight', (_message.Message,), dict(
  DESCRIPTOR = _LANETRAFFICLIGHT,
  __module__ = 'modules.v2x.proto.v2x_obu_traffic_light_pb2'
  # @@protoc_insertion_point(class_scope:apollo.v2x.obu.LaneTrafficLight)
  ))
_sym_db.RegisterMessage(LaneTrafficLight)

RoadTrafficLight = _reflection.GeneratedProtocolMessageType('RoadTrafficLight', (_message.Message,), dict(
  DESCRIPTOR = _ROADTRAFFICLIGHT,
  __module__ = 'modules.v2x.proto.v2x_obu_traffic_light_pb2'
  # @@protoc_insertion_point(class_scope:apollo.v2x.obu.RoadTrafficLight)
  ))
_sym_db.RegisterMessage(RoadTrafficLight)

ObuTrafficLight = _reflection.GeneratedProtocolMessageType('ObuTrafficLight', (_message.Message,), dict(
  DESCRIPTOR = _OBUTRAFFICLIGHT,
  __module__ = 'modules.v2x.proto.v2x_obu_traffic_light_pb2'
  # @@protoc_insertion_point(class_scope:apollo.v2x.obu.ObuTrafficLight)
  ))
_sym_db.RegisterMessage(ObuTrafficLight)


# @@protoc_insertion_point(module_scope)
