# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/v2x/proto/v2x_rsi.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from modules.common.proto import header_pb2 as modules_dot_common_dot_proto_dot_header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/v2x/proto/v2x_rsi.proto',
  package='apollo.v2x',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x1fmodules/v2x/proto/v2x_rsi.proto\x12\napollo.v2x\x1a!modules/common/proto/header.proto\" \n\x08RsiPoint\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\"\xd4\x01\n\x06RsiMsg\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.apollo.common.Header\x12$\n\x06points\x18\x02 \x03(\x0b\x32\x14.apollo.v2x.RsiPoint\x12\r\n\x05speed\x18\x03 \x01(\x01\x12\x11\n\tlow_speed\x18\x04 \x01(\x01\x12\x12\n\nhigh_speed\x18\x05 \x01(\x01\x12\x13\n\x0b\x64\x65scription\x18\x06 \x01(\t\x12\x10\n\x08rsi_type\x18\x07 \x01(\x05\x12\x0e\n\x06radius\x18\x08 \x01(\x01\x12\x10\n\x08priority\x18\t \x01(\x05')
  ,
  dependencies=[modules_dot_common_dot_proto_dot_header__pb2.DESCRIPTOR,])




_RSIPOINT = _descriptor.Descriptor(
  name='RsiPoint',
  full_name='apollo.v2x.RsiPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='apollo.v2x.RsiPoint.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='apollo.v2x.RsiPoint.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=114,
)


_RSIMSG = _descriptor.Descriptor(
  name='RsiMsg',
  full_name='apollo.v2x.RsiMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='apollo.v2x.RsiMsg.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='points', full_name='apollo.v2x.RsiMsg.points', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='speed', full_name='apollo.v2x.RsiMsg.speed', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='low_speed', full_name='apollo.v2x.RsiMsg.low_speed', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='high_speed', full_name='apollo.v2x.RsiMsg.high_speed', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='apollo.v2x.RsiMsg.description', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rsi_type', full_name='apollo.v2x.RsiMsg.rsi_type', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='radius', full_name='apollo.v2x.RsiMsg.radius', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='priority', full_name='apollo.v2x.RsiMsg.priority', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=329,
)

_RSIMSG.fields_by_name['header'].message_type = modules_dot_common_dot_proto_dot_header__pb2._HEADER
_RSIMSG.fields_by_name['points'].message_type = _RSIPOINT
DESCRIPTOR.message_types_by_name['RsiPoint'] = _RSIPOINT
DESCRIPTOR.message_types_by_name['RsiMsg'] = _RSIMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RsiPoint = _reflection.GeneratedProtocolMessageType('RsiPoint', (_message.Message,), dict(
  DESCRIPTOR = _RSIPOINT,
  __module__ = 'modules.v2x.proto.v2x_rsi_pb2'
  # @@protoc_insertion_point(class_scope:apollo.v2x.RsiPoint)
  ))
_sym_db.RegisterMessage(RsiPoint)

RsiMsg = _reflection.GeneratedProtocolMessageType('RsiMsg', (_message.Message,), dict(
  DESCRIPTOR = _RSIMSG,
  __module__ = 'modules.v2x.proto.v2x_rsi_pb2'
  # @@protoc_insertion_point(class_scope:apollo.v2x.RsiMsg)
  ))
_sym_db.RegisterMessage(RsiMsg)


# @@protoc_insertion_point(module_scope)
